openapi: 3.0.0
info:
  title: 1.1 - OpenAPI 3.0
  description: |
    STD22026
  version: 1.0.11
servers:
  - url: https://STD22026.com
tags:
  - name : students
    description: Everything about your students
  - name: teachers
    description: Everything about your teachers
paths:
  /students:
    get:
      tags:
        - students
      summary: Retrieve students
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags :
        - students
      summary: Add new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags :
        - students
      summary: Update student
      description: Update status information with additional properties
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusUpdateRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - students
      summary: Delete student
      description: Delete status information based on certain criteria
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /teachers:
    get:
      tags :
        - teachers
      summary: Retrieve teacher information
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags :
        - teachers
      summary: Add new teacher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeacherRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    StatusResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Rasoa
        Birthday:
          type: string
          format: date
          example: "2000-01-01"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Internet several error"
    StatusRequest:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        Birthday:
          type: string
          format: date
    StatusUpdateRequest:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
        Birthday:
          type: string
          format: date
        additionalProperty:
          type: string
          description: Additional property for update
    TeacherResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        first_name:
          type: string
          example: Tokimahery
        last_name:
          type: string
          example: Ramarozaka
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'
    Course:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        duration:
          type: integer
      example:
        - name: Algo
          code: prog1
          duration: 20 heures
        - name: Développement WEB
          code: WEB1
          duration: 28 heures
    TeacherRequest:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'


